name: 清除缓存

on: 
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 清除缓存
      run: |
        curl https://purge.jsdelivr.net/gh/wayne0926/hexo-blog@gh-pages/js/main.js
        curl https://purge.jsdelivr.net/gh/wayne0926/hexo-blog@gh-pages/js/main.min.js
        curl https://purge.jsdelivr.net/gh/wayne0926/hexo-blog@gh-pages/css/index.css
        curl https://purge.jsdelivr.net/gh/wayne0926/hexo-blog@gh-pages/css/index.min.css
        echo -e '\n\n请求完成'
