name: 清除缓存

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 清除缓存
      run: |
        curl https://purge.jsdelivr.net/gh/wayne0926/hexo-blog@gh-pages/main.css
        curl https://purge.jsdelivr.net/gh/wayne0926/hexo-blog@gh-pages/main.min.css
        curl https://purge.jsdelivr.net/gh/wayne0926/hexo-blog@gh-pages/index.css
        curl https://purge.jsdelivr.net/gh/wayne0926/hexo-blog@gh-pages/index.min.css
