name: 清除缓存

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: CLEANTEMP
      run: |
        curl https://purge.jsdelivr.net/gh/wayne0926/hexo-blog@gh-pages/main.css
        curl https://purge.jsdelivr.net/gh/wayne0926/hexo-blog@gh-pages/index.css
